### ISSUE TITLE
Repository can't directly be used as library

### ISSUE THREAD

**Issue by leah-u** [redbasecap/Stepper_28BYJ-48_with_ULN2003_Driver_Libary#3]
If you rename the repository so it doesn't begin with a number and move the library files to the top directory, it will be possible to clone the repository directly into the Arduino libraries folder.

**Comment by per1234** [comment]
With Arduino IDE 1.8.4 and newer, library folders are allowed to start with a number:
https://github.com/arduino/Arduino/commit/4545283ae773b6351d089e37b6d4080905ea8fd5
So you need to test with Arduino IDE 1.8.3 or older to see the problem that would be caused by leaving the repository name as-is.

I agree that it's best to store the library in the root of the repository. In addition to the advantage @fulmsch already mentioned, there are a couple others that are even more important to the average Arduino user:
- Allows installing the library in the Arduino IDE from the .zip file download of the repository via **Sketch > Include Library > Add .ZIP Library**.
- Allows inclusion in the [Arduino Library Manager index](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ). This provides an even easier installation via **Sketch > Include Library > Manage Libraries** and a much easier way to update the library to new versions.

**Comment by redbasecap** [comment]
I fixed this problem, and thanks to fulmsch for the pullrequest!

**Comment by redbasecap** [comment]
> 
> 
> With Arduino IDE 1.8.4 and newer, library folders are allowed to start with a number:
> [arduino/Arduino@4545283](https://github.com/arduino/Arduino/commit/4545283ae773b6351d089e37b6d4080905ea8fd5)
> So you need to test with Arduino IDE 1.8.3 or older to see the problem that would be caused by leaving the repository name as-is.
> 
> I agree that it's best to store the library in the root of the repository. In addition to the advantage @fulmsch already mentioned, there are a couple others that are even more important to the average Arduino user:
> 
>     * Allows installing the library in the Arduino IDE from the .zip file download of the repository via **Sketch > Include Library > Add .ZIP Library**.
> 
>     * Allows inclusion in the [Arduino Library Manager index](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ). This provides an even easier installation via **Sketch > Include Library > Manage Libraries** and a much easier way to update the library to new versions.

Thanks for your comment, the libary is now improved to use.
Greetins redbasecap
